import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

/// Firebase-backed repository for the Lifeline production app.
///
/// Call these methods after `Firebase.initializeApp()` (generated by
/// `flutterfire configure`). The presentation currently uses local demo data,
/// so the app remains runnable until a Firebase project is connected.
class FirebaseMatchService {
  FirebaseMatchService({FirebaseFirestore? firestore, FirebaseAuth? auth})
      : _db = firestore ?? FirebaseFirestore.instance,
        _auth = auth ?? FirebaseAuth.instance;

  final FirebaseFirestore _db;
  final FirebaseAuth _auth;

  Future<UserCredential> signInAnonymously() => _auth.signInAnonymously();

  Future<void> saveDonorProfile({
    required String bloodType,
    required String city,
    required String area,
    required bool available,
    required String language,
  }) async {
    final uid = _requireUser();
    await _db.collection('donors').doc(uid).set({
      'bloodType': bloodType,
      'city': city,
      'area': area,
      'available': available,
      'language': language,
      'updatedAt': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
  }

  Stream<QuerySnapshot<Map<String, dynamic>>> urgentRequests({
    required String city,
    required String bloodType,
  }) {
    // The Cloud Function only notifies compatible donors; this query supplies
    // the live in-app request board. Add a geohash filter for city-scale use.
    return _db
        .collection('requests')
        .where('city', isEqualTo: city)
        .where('isOpen', isEqualTo: true)
        .where('compatibleTypes', arrayContains: bloodType)
        .orderBy('createdAt', descending: true)
        .snapshots();
  }

  Future<DocumentReference<Map<String, dynamic>>> createRequest({
    required String hospital,
    required String city,
    required String bloodType,
    required int units,
    required bool isUrgent,
  }) {
    return _db.collection('requests').add({
      'hospital': hospital,
      'city': city,
      'bloodType': bloodType,
      'compatibleTypes': compatibleDonorsFor(bloodType),
      'units': units,
      'isUrgent': isUrgent,
      'isOpen': true,
      'createdBy': _requireUser(),
      'createdAt': FieldValue.serverTimestamp(),
    });
  }

  Future<void> saveMessagingToken() async {
    final uid = _requireUser();
    final settings = await FirebaseMessaging.instance.requestPermission();
    if (settings.authorizationStatus == AuthorizationStatus.denied) return;
    final token = await FirebaseMessaging.instance.getToken();
    if (token != null) {
      await _db.collection('donors').doc(uid).set({
        'fcmTokens': FieldValue.arrayUnion([token]),
      }, SetOptions(merge: true));
    }
  }

  String _requireUser() {
    final uid = _auth.currentUser?.uid;
    if (uid == null) throw StateError('A signed-in user is required.');
    return uid;
  }
}

/// Red cells a donor type can provide for a recipient request.
List<String> compatibleDonorsFor(String recipientType) => switch (recipientType) {
  'O-' => ['O-'],
  'O+' => ['O-', 'O+'],
  'A-' => ['O-', 'A-'],
  'A+' => ['O-', 'O+', 'A-', 'A+'],
  'B-' => ['O-', 'B-'],
  'B+' => ['O-', 'O+', 'B-', 'B+'],
  'AB-' => ['O-', 'A-', 'B-', 'AB-'],
  'AB+' => ['O-', 'O+', 'A-', 'A+', 'B-', 'B+', 'AB-', 'AB+'],
  _ => <String>[],
};
